import * as D from './domain.mjs';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'M3 11 12 3l9 8M5 10v10h5v-6h4v6h5V10',calendar:'M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2ZM7 2v4m10-4v4M3 10h18m-13 4h2m4 0h2m-8 3h2',phone:'M8 3 4 5c-3 7 8 18 15 15l2-4-5-3-2 3c-3-1-5-3-6-6l3-2Z',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m18 0v-2a4 4 0 0 0-3-4M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8m8 1a4 4 0 0 1 0 7',file:'M5 3h10l4 4v14H5ZM14 3v5h5M8 12h8m-8 4h8',wallet:'M3 6h18v14H3Zm0 0 15-3v3m-4 6h7v5h-7Zm3 2h1',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',arrow:'m9 5 7 7-7 7',check:'m5 12 4 4L19 6'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.home}"/></svg>`;
const tabs=[['home','home','오늘의 스튜디오'],['schedule','calendar','일정 관리'],['inquiries','phone','문의함'],['customers','people','고객 관리'],['applications','file','상담 신청서'],['payments','wallet','입금 관리'],['settings','settings','설정']];
let installedThisSession=false;
let view='home',selectedDate=D.today(),data={students:[],logs:[],weekOvr:{},consults:[],payments:[],inquiries:[]},session=null,sync=null,hydrated=false,submitting=false,formContext=null,toastTimer,search='';
const modeLabels={synced:'서버 저장 확인됨',recovery:'서버 저장 확인됨 · 이전 보관본 유지',saving:'서버 저장 확인 중',pending:'변경 전송 대기',deferred:'작성 중 · 다른 기기 변경은 잠시 보관',offline:'연결 끊김 · 보관된 변경 확인 필요','auth-required':'관리자 로그인 필요','missing-remote':'서버 자료 없음 · 자동 생성하지 않습니다','invalid-remote':'서버 자료 확인 필요',conflict:'동시 수정 충돌 · 변경 보관 중','legacy-conflict':'기존 변경 충돌 · 확인 필요','storage-error':'기기 저장 실패 · 작성 내용을 보존하세요','apply-error':'화면 반영 실패 · 보관본 유지','write-error':'서버 저장 실패 · 변경 보관 중',unconfirmed:'서버 확인 중','local-only':'서버 미확인 · 이 기기에 보관'};
function notify(message){clearTimeout(toastTimer);$('toast').hidden=false;$('toast').textContent=message;toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
function stateReady(){return !!session&&hydrated&&sync?.ready&&!sync.blocked&&VCFTransport.stateMode()==='active';}
function cachedKey(){return 'hlb-v2-cache:'+session?.principal;}
function draftKey(){return session&&formContext?'hlb-v2-draft:'+session.principal+':'+formContext.type+':'+formContext.draftId:null;}
function paintStatus(mode=sync?.mode||'unconfirmed',detail){$('connection').dataset.mode=mode;$('connection').textContent=modeLabels[mode]||'상태 확인 필요';if(sync?.pending())$('connection').textContent+=' · '+sync.pending()+'건';if(mode==='write-error'&&typeof detail==='string'&&/[가-힣]/.test(detail))notify(detail);if(!hydrated&&['missing-remote','invalid-remote','offline','storage-error'].includes(mode))$('main').innerHTML=`<div class="loading"><h1>고객 자료를 확인할 수 없습니다.</h1><p>${esc(modeLabels[mode])}. 기존 자료를 덮어쓰거나 새로 생성하지 않습니다.</p>${button('다시 확인','refresh',{},'primary')}</div>`;}
function empty(text='아직 등록된 내용이 없습니다.',sub='새로운 기록을 만들면 이곳에 표시됩니다.'){return `<div class="empty"><strong>${esc(text)}</strong>${esc(sub)}</div>`;}
function badge(e){return `<span class="badge ${e.scheduleType==='flex'?'flex':e.kind!=='lesson'?'consult':''}">${e.completed?'상담 완료':e.cancelled?'취소':e.kind!=='lesson'?'상담':e.scheduleType==='flex'?'변동':'고정'}</span>`;}
function button(label,action,payload={},className='secondary'){return `<button type="button" class="${className}" data-action="${action}" data-payload="${esc(JSON.stringify(payload))}">${esc(label)}</button>`;}
function header(title,subtitle,actions=''){return `<section class="page-title"><div><span class="eyebrow">STUDIO / ${view.toUpperCase()}</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${actions||`<div class="date-label"><span></span>${esc(D.today().replaceAll('-','.'))}</div>`}</section>`;}
function nav(){for(const [id,target]of [['navigation',tabs],['mobile-navigation',tabs.filter(x=>['home','schedule','inquiries','customers','settings'].includes(x[0]))]])$(id).innerHTML=target.map(([key,ic,label])=>`<button class="nav-item ${view===key?'active':''}" data-action="navigate" data-view="${key}" ${view===key?'aria-current="page"':''}>${icon(ic)}<span>${esc(key==='home'?'대시보드':label)}</span></button>`).join('');$('breadcrumb').textContent=tabs.find(t=>t[0]===view)?.[2]||'';}
function kpis(){const events=D.eventsForWeek(data,D.today()).filter(e=>e.date===D.today()&&!e.cancelled),values=[['phone','미처리 문의',data.inquiries.filter(q=>!q.consultId).length,'건','문의 → 상담'],['calendar','오늘의 일정',events.length,'건','스튜디오 일정'],['people','수강중 고객',data.students.filter(s=>s.status==='수강중').length,'명','현재 등록 기준'],['wallet','이번 달 입금',data.payments.filter(p=>(p.date||'').startsWith(D.today().slice(0,7))).reduce((n,p)=>n+(Number(p.amount)||0),0).toLocaleString('ko-KR'),'원','입금 기록 기준']];return `<div class="kpis">${values.map(([ic,label,value,unit,note])=>`<article class="kpi"><div class="kpi-label">${icon(ic)}${label}</div><div class="kpi-value">${value}<small>${unit}</small></div><div class="kpi-note">${note}</div></article>`).join('')}</div>`;}
function calendar(){const mon=D.monday(selectedDate),events=D.eventsForWeek(data,selectedDate).filter(e=>!e.cancelled),outside=events.filter(e=>D.minutes(e.time)<540||D.minutes(e.time)+e.duration>1260);
 const dayColumns=D.DAYS.map((day,i)=>{const date=D.addDays(mon,i);return `<div class="day-column ${date===D.today()?'is-today':''}">${events.filter(e=>e.date===date&&D.minutes(e.time)>=540&&D.minutes(e.time)<1260).map(e=>`<button class="calendar-event ${e.scheduleType==='flex'?'flex':e.kind!=='lesson'?'consult':''} ${e.completed?'done':''}" style="top:${(D.minutes(e.time)-540)/720*100}%;height:${Math.max(e.duration/720*100,5)}%" data-action="event" data-payload="${esc(JSON.stringify({key:e.key}))}" title="${esc(e.name+' '+e.date+' '+e.time)}"><strong>${esc(e.name)}</strong><small>${e.time} · ${e.duration}분</small></button>`).join('')}</div>`}).join('');
 const dayEvents=events.filter(e=>e.date===selectedDate);
 return `<article class="panel"><div class="panel-heading"><h3>주간 스케줄 <span>${mon.slice(5)} — ${D.addDays(mon,6).slice(5)}</span></h3><div class="calendar-controls">${button('‹','week-prev')}${button('오늘','today')}${button('›','week-next')}${button('일정 등록','schedule.once',{},'primary')}</div></div><div class="legend"><span>고정 수업</span><span>변동 수업</span><span>상담 예약</span></div><div class="calendar-desktop"><div class="week-head"><div></div>${D.DAYS.map((day,i)=>`<div class="${D.addDays(mon,i)===D.today()?'is-today':''}">${day}<strong>${D.addDays(mon,i).slice(8)}</strong></div>`).join('')}</div><div class="week-body"><div class="hour-rail">${Array.from({length:12},(_,i)=>`<span style="top:${i/12*100}%">${String(i+9).padStart(2,'0')}:00</span>`).join('')}</div>${dayColumns}</div></div><div class="agenda"><div class="day-strip">${D.DAYS.map((day,i)=>`<button data-action="day" data-date="${D.addDays(mon,i)}" class="${selectedDate===D.addDays(mon,i)?'selected':''}">${day}<b>${D.addDays(mon,i).slice(8)}</b></button>`).join('')}</div>${dayEvents.map(e=>`<button class="agenda-row" style="background:none;color:inherit;border:0;border-bottom:1px solid var(--border);text-align:left;width:100%" data-action="event" data-payload="${esc(JSON.stringify({key:e.key}))}"><span class="agenda-time">${e.time}</span><div><div class="event-name">${esc(e.name)}</div><p>${e.duration}분 · ${e.kind==='lesson'?'보컬 레슨':'방문 상담'}</p></div>${badge(e)}</button>`).join('')||empty('이날 등록된 일정이 없습니다.','일정 등록 버튼에서 추가하세요.')}</div><div class="panel-foot"><span>${events.length}개 일정 · Asia/Seoul${outside.length?' · 표시 시간 밖 '+outside.length+'건':''}</span>${button('고정 일정 설정','schedule.fixed',{},'text-button')}</div>${outside.length?`<div class="panel-body">${outside.map(e=>button(`${e.date} ${e.time} ${e.name}`,'event',{key:e.key},'text-button')).join('')}</div>`:''}</article>`;
}
function recentInquiries(){return `<article class="panel"><div class="panel-heading"><h3>최근 문의</h3>${button('전체 보기','navigate-inquiries',{},'text-button')}</div>${data.inquiries.slice(0,4).map(q=>`<div class="inquiry-item"><span class="avatar">${esc((q.name||'문').slice(0,1))}</span><div><strong>${esc(q.name||q.phone)}</strong><p>${esc((q.memo||q.phone||'전화 문의').slice(0,55))}</p><small>${esc(q.date||'날짜 미등록')}</small></div>${button('보기','inquiry',{id:q.id},'text-button')}</div>`).join('')||empty('최근 문의가 없습니다.','전화번호만 입력해 바로 저장하세요.')}</article>`;}
function dashboard(){return header('오늘의 스튜디오','수업의 흐름을 놓치지 않도록, 필요한 일만 한눈에.')+kpis()+`<div class="dashboard-grid"><div>${calendar()}</div><aside class="right-column"><section class="quick-card"><span class="call-orb">${icon('phone')}</span><h3>한 통의 전화, 하나의 연결.</h3><p>전화번호만 먼저 저장하세요.<br>상담 예약과 신청서로 자연스럽게 이어집니다.</p>${button('전화 문의 빠른 저장','inquiry.save',{},'primary')}</section>${recentInquiries()}<article class="panel flow-card"><h3>스튜디오 운영 흐름</h3><div class="flow-row"><b>01</b> 문의를 남기고<small>빠른 저장</small></div><div class="flow-row"><b>02</b> 상담 일정을 잡고<small>일정 반영</small></div><div class="flow-row"><b>03</b> 신청서를 작성하고<small>고객 등록</small></div><div class="flow-row"><b>04</b> 수업을 이어갑니다<small>고정 · 변동</small></div></article></aside></div>`;}
function matches(row){const s=search.replace(/[\s-]/g,'').toLowerCase();return !s||[row.name,row.ph,row.phone].some(v=>String(v||'').replace(/[\s-]/g,'').toLowerCase().includes(s));}
function table(headers,items){return `<div class="panel table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${items.join('')}</tbody></table>${items.length?'':empty('검색 결과가 없거나 아직 등록된 내용이 없습니다.')}</div>`;}
function person(row){return `<div class="person-cell"><span class="avatar">${esc((row.name||'고').slice(0,1))}</span><div>${esc(row.name||row.phone||'이름 미등록')}<small>${esc(row.ph||row.phone||'연락처 미등록')}</small></div></div>`;}
function customerPage(){return header('사람을 더 가까이.','문의부터 수업까지 이어지는 고객의 기록.',`<div class="view-actions">${button('고객 등록','student.create',{},'primary')}</div>`)+table(['고객','상태','수업 일정','관리'],data.students.filter(matches).map(s=>`<tr><td>${person(s)}</td><td><span class="badge ${s.status==='수강중'?'':'muted'}">${esc(s.status||'상태 미등록')}</span></td><td>${s.schedType==='flex'?'변동 일정':esc((s.days||[]).map(d=>d+' '+(s.times?.[d]||'')).join(' · ')||'일정 미등록')}</td><td><div class="row-actions">${button('상세','student',{id:s.id})}${button('일정 등록','schedule.once',{studentId:s.id})}</div></td></tr>`));}
function inquiryPage(){return header('놓치지 않는 첫 만남.','번호만 먼저 저장하고, 상담과 신청서로 연결하세요.',`<div class="view-actions">${button('문의 등록','inquiry.save',{},'primary')}</div>`)+table(['문의자','문의 내용','방문 예약','다음 단계'],data.inquiries.filter(matches).map(q=>`<tr><td>${person(q)}</td><td>${esc((q.memo||'전화 문의').slice(0,80))}</td><td>${q.consultId?'<span class="badge">신청서 작성됨</span>':esc(q.visitDate?(q.visitDate+' '+(q.visitTime||'')):'예약 전')}</td><td><div class="row-actions">${button('상세','inquiry',{id:q.id})}${!q.consultId?button('상담 예약','inquiry.book',{id:q.id}):''}</div></td></tr>`));}
function applicationPage(){return header('상담을 기록으로.','고객의 목표, 경험과 상담 내용을 한 장에 보관합니다.',`<div class="view-actions">${button('신청서 작성','application.save',{},'primary')}</div>`)+table(['신청자','작성일','상담 목표','관리'],data.consults.filter(matches).map(c=>`<tr><td>${person(c)}</td><td>${esc(c.date||'날짜 미등록')}</td><td>${esc((c.goal||c.memo||'기존 상담 기록').slice(0,80))}</td><td><div class="row-actions">${button('신청서 보기','application',{id:c.id})}${button('고객 등록','student.create',{name:c.name,phone:c.phone,course:c.cls})}</div></td></tr>`));}
function paymentPage(){return header('입금 기록을 명확하게.','결제 대행이 아닌, 스튜디오 입금 내역을 관리합니다.',`<div class="view-actions">${button('입금 기록','payment.add',{},'primary')}</div>`)+table(['고객','입금일','금액','메모'],data.payments.map(p=>{const row=data.students.find(s=>s.id===(p.sid||p.studentId));return `<tr><td>${esc(row?.name||p.name||'고객 확인 필요')}</td><td>${esc(p.date||'')}</td><td>${(Number(p.amount)||0).toLocaleString('ko-KR')}원</td><td>${esc(p.memo||'')}</td></tr>`;}));}
function settingsPage(){return header('조용하게, 정확하게.','연결과 저장 상태를 숨기지 않습니다.')+`<div class="settings-grid"><article class="panel"><div class="panel-body"><h3>서버와 동기화</h3><dl><dt>현재 상태</dt><dd>${esc(modeLabels[sync?.mode]||'연결 중')}</dd><dt>서버 버전 / 전송 대기</dt><dd>${sync?.state?.revision??'확인 전'} / ${sync?.pending()||0}건</dd><dt>계정</dt><dd>${esc(session?.email||'로그인 필요')}</dd></dl><p>휴대폰과 PC는 같은 Cloudflare 데이터를 사용합니다. 변경 알림과 재접속 확인을 사용하며, 매초 반복 조회하지 않습니다.</p><div class="view-actions">${button('다시 확인','refresh')}${button('기기 보관본 내보내기','export')}${sync?.mode==='conflict'||sync?.mode==='legacy-conflict'?button('서버 기준으로 복구','recover',{},'danger'):''}</div></div></article><article class="panel"><div class="panel-body"><h3>설치된 스튜디오 앱</h3><p id="install-help">Chrome 또는 Edge 메뉴에서 앱 설치를 선택하세요. iPhone/iPad는 Safari의 공유 → 홈 화면에 추가를 사용합니다. 브라우저가 설치 가능 상태를 알릴 때만 설치 창을 열 수 있습니다.</p>${button('앱 설치 / 안내','install',{},'primary')}<p>새 앱 실행에는 인터넷 연결이 필요합니다. 미전송 초안이 있을 때 기기 저장소를 삭제하지 마세요.</p></div></article><article class="panel"><div class="panel-body"><h3>전화 문의 저장</h3><p>전화번호를 입력하고 Enter를 누르면 빠르게 저장합니다. 휴대폰 수신 번호 자동 감지는 아직 연결되어 있지 않습니다. 통신사·전화 시스템 연결 없이 자동 수신을 표시하지 않습니다.</p>${button('전화 문의 등록','inquiry.save')}</div></article><article class="panel"><div class="panel-body"><h3>기존 업무와 데이터 보존</h3><p>기존 레슨 기록, 출결, 미디어와 상세 고객 편집은 기존 관리 화면에서 이용할 수 있습니다. V2와 같은 서버를 사용하며, Firebase 원본을 초기화하지 않습니다.</p><a class="secondary" href="/index.html">기존 관리 화면</a> ${button('로그아웃','logout',{},'ghost')}</div></article></div>`;}
function render(){nav();if(!hydrated){if(!session)$('main').innerHTML=`<div class="loading"><h1>관리자 연결을 확인해 주세요.</h1><p>로그인 후 실제 고객과 일정을 표시합니다.</p><a class="primary" href="/v2/">로그인 / 다시 연결</a></div>`;return;}const pages={home:dashboard,schedule:()=>header('일정을 더 선명하게.','고정 수업과 이번 주의 변동을 구분해서 관리하세요.',`<div class="view-actions">${button('고정 일정','schedule.fixed',{},'secondary')}</div>`)+calendar(),customers:customerPage,inquiries:inquiryPage,applications:applicationPage,payments:paymentPage,settings:settingsPage};$('main').innerHTML=(pages[view]||dashboard)();paintStatus();paintInstall();}
function field(name,label,type='text',value='',required=false){return `<label class="field">${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='tel'?'autocomplete="tel" inputmode="tel"':''}></label>`;}
function area(name,label,value=''){return `<label class="field">${esc(label)}<textarea name="${name}">${esc(value)}</textarea></label>`;}
function studentSelect(selected){return `<label class="field">고객 선택<select name="studentId" required><option value="">고객을 선택해 주세요</option>${data.students.filter(s=>s.status==='수강중').map(s=>`<option value="${esc(s.id)}" ${String(s.id)===String(selected)?'selected':''}>${esc(s.name)} · ${esc(s.ph||s.phone||'')}</option>`).join('')}</select></label>`;}
function timeFields(p={}){return `<div class="field-row">${field('date','날짜','date',p.date||selectedDate,true)}${field('time','시작 시간','time',p.time||'14:00',true)}</div>${field('duration','소요 시간 (분)','number',p.duration||50,true)}`;}
const titles={'inquiry.save':'전화 문의 빠른 저장','inquiry.book':'방문 상담 예약','application.save':'상담 신청서 작성','student.create':'고객 등록','schedule.once':'변동 일정 등록','schedule.fixed':'고정 일정 설정','schedule.move':'이번 일정 변경','payment.add':'입금 기록'};
function openForm(type,payload={}){
 if(!stateReady()){notify('먼저 서버 연결과 저장 상태를 확인해 주세요. 입력 중 초안은 같은 입력 화면을 다시 열어 복구할 수 있습니다.');return;}
 const p={...payload};if(['inquiry.save','application.save','student.create','payment.add'].includes(type)&&!p.id)p.id=crypto.randomUUID();
 if(type==='inquiry.save'&&payload.id)Object.assign(p,data.inquiries.find(q=>q.id===payload.id));
 if(type==='application.save'&&p.inquiryId){const q=data.inquiries.find(x=>x.id===p.inquiryId);Object.assign(p,{name:q?.name===q?.phone?'':q?.name,phone:q?.phone,notes:q?.memo});}
 formContext={type,payload:p,draftId:payload.id||payload.studentId||payload.inquiryId||payload.eventKey||'new'};$('dialog-title').textContent=titles[type]||'기록';$('dialog-step').textContent=type.startsWith('inquiry')?'01 / INQUIRY':type.startsWith('application')?'03 / APPLICATION':'STUDIO / WORKFLOW';
 let fields='';
 if(type==='inquiry.save')fields=`<div class="help-box">이름을 몰라도 괜찮습니다. 번호를 먼저 저장하고 나머지는 통화 후 채우세요.</div>${field('phone','전화번호','tel',p.phone,true)}${field('name','이름 (선택)','text',p.name)}${area('memo','문의 메모',p.memo)}`;
 if(type==='inquiry.book')fields=`<div class="help-box">예약하면 오늘 / 주간 일정에 바로 연결됩니다. 다른 확정 일정과 겹치면 저장하지 않습니다.</div>${timeFields({...p,duration:p.duration||30})}`;
 if(type==='application.save')fields=`<div class="field-row">${field('name','이름','text',p.name,true)}${field('phone','연락처','tel',p.phone,true)}</div>${field('course','희망 수업','text',p.course||'보컬 레슨')}${area('goal','상담 목표 (필수)',p.goal)}${area('experience','수업 경험',p.experience)}${area('notes','상담 내용',p.notes)}<label class="field-check"><input type="checkbox" name="confirmed" required>담당자가 작성 내용을 확인했습니다. 고객 등록은 신청서 저장 후 별도로 진행합니다.</label>`;
 if(type==='student.create')fields=`<div class="field-row">${field('name','이름','text',p.name,true)}${field('phone','연락처','tel',p.phone,true)}</div>${field('course','수업 과정','text',p.course||'hob')}<div class="help-box">수강중 고객으로 등록합니다. 수업 시간은 이후 일정 등록에서 지정합니다. 같은 번호의 고객은 중복 등록하지 않습니다.</div>`;
 if(type==='schedule.once')fields=`${studentSelect(p.studentId)}${timeFields(p)}<div class="help-box">이 날짜에만 추가됩니다. 기존 고정 일정은 그대로 유지됩니다.</div>`;
 if(type==='schedule.fixed')fields=`${studentSelect(p.studentId)}<div class="field-row">${field('start','시작일','date',selectedDate,true)}${field('end','종료일','date',D.addDays(selectedDate,84),true)}</div><div class="field"><span>매주 반복 요일</span><div class="days-select">${D.DAYS.map(d=>`<label><input type="checkbox" name="days" value="${d}">${d}</label>`).join('')}</div></div><div class="field-row">${field('time','시작 시간','time','14:00',true)}${field('duration','소요 시간 (분)','number',50,true)}</div><div class="help-box">최대 2년까지 설정할 수 있습니다. 해당 기간의 중복 예약을 검사하며, 이전 기간의 고정 일정은 보존합니다. 이미 설정한 주별 예외가 우선합니다.</div>`;
 if(type==='schedule.move')fields=`${timeFields(p)}<div class="help-box">선택한 한 번의 일정만 변경합니다. 원래 시간은 취소 이력으로 보존됩니다.</div>`;
 if(type==='payment.add')fields=`${studentSelect(p.studentId)}<div class="field-row">${field('amount','입금액 (원)','number','',true)}${field('date','입금일','date',D.today(),true)}</div>${area('memo','입금 메모')}<div class="help-box">실제 결제를 요청하지 않고, 입금 사실만 기록합니다.</div>`;
 $('dialog-body').innerHTML=`<form id="action-form">${fields}<div class="draft-note" id="draft-status">초안은 현재 계정의 기기에만 보관됩니다.</div><p class="form-error" id="form-error" role="alert"></p><div class="form-actions">${button('닫기','close',{},'ghost')}<button type="submit" class="primary">${type==='application.save'?'신청서 저장':'저장하기'}</button></div></form>`;
 try{const raw=localStorage.getItem(draftKey());if(raw){const saved=JSON.parse(raw);if(saved._recordId&&!payload.id)formContext.payload.id=saved._recordId;for(const input of $('action-form').elements){if(!input.name||!own(saved,input.name))continue;if(input.type==='checkbox')input.checked=Array.isArray(saved[input.name])?saved[input.name].includes(input.value):saved[input.name]===true;else input.value=saved[input.name];}$('draft-status').textContent='이 기기의 작성 중 초안을 복구했습니다. 아직 서버에 저장되지 않았습니다.';}}catch{}
 const form=$('action-form');form.addEventListener('input',saveDraft);form.addEventListener('submit',submitForm);if(!$('editor').open)$('editor').showModal();setTimeout(()=>form.querySelector('input,select,textarea')?.focus(),30);
}
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
function formValues(){const f=$('action-form'),values=Object.fromEntries(new FormData(f));if(f.querySelector('[name=days]'))values.days=new FormData(f).getAll('days');if(f.elements.confirmed)values.confirmed=f.elements.confirmed.checked;return values;}
function saveDraft(){const key=draftKey();if(!key)return;try{localStorage.setItem(key,JSON.stringify({...formValues(),_recordId:formContext.payload.id}));$('draft-status').textContent='초안 보관됨 · 서버 저장 전';}catch{$('draft-status').textContent='초안 보관 실패 · 저장 공간을 확인하고 입력 내용을 별도로 보존하세요.';}}
async function submitForm(event){event.preventDefault();if(submitting)return;const form=$('action-form');if(!form.reportValidity())return;const key=draftKey();let next;try{next=D.applyAction(data,{type:formContext.type,payload:{...formContext.payload,...formValues()}});}catch(error){$('form-error').textContent=error.message;return;}
 submitting=true;form.querySelector('[type=submit]').disabled=true;data=next;
 try{const ok=await sync.save();if(sync.hold==='storage'){$('form-error').textContent='기기 저장에 실패했습니다. 입력 내용을 유지하고 저장 공간을 확인해 주세요.';return;}if(key){try{localStorage.removeItem(key);}catch{}}$('editor').close();formContext=null;render();notify(ok&&sync.pending()===0?'서버에 저장했습니다.':'변경을 보관했습니다. 서버 전송 대기 상태를 확인해 주세요.');}
 catch(error){$('form-error').textContent='저장 확인이 필요합니다. 초안을 유지했습니다. '+error.message;}finally{submitting=false;if(form.isConnected)form.querySelector('[type=submit]').disabled=false;sync?.drain();}
}
function showDetail(title,entries,actions=''){formContext=null;$('dialog-title').textContent=title;$('dialog-step').textContent='STUDIO / RECORD';$('dialog-body').innerHTML=`<dl class="detail-list">${entries.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value||'—')}</dd></div>`).join('')}</dl><div class="view-actions">${actions}</div>`;if(!$('editor').open)$('editor').showModal();}
function showEvent(key){const e=D.eventsForWeek(data,JSON.parse(key)[2]).find(x=>x.key===key);if(!e)return notify('최신 일정을 다시 선택해 주세요.');showDetail(e.name,[['날짜',e.date],['시간',`${e.time} / ${e.duration}분`],['구분',e.kind==='lesson'?(e.scheduleType==='fixed'?'고정 수업':'이번 주 변동'):'방문 상담'],['상태',e.cancelled?'취소':e.completed?'상담 완료':'예약됨']],!e.completed&&!e.cancelled?button('일정 변경','schedule.move',{eventKey:key,date:e.date,time:e.time,duration:e.duration},'primary')+button('이번 일정 취소','cancel',{key},'danger')+(e.kind==='inquiry'?button('신청서 작성','application.save',{inquiryId:e.ownerId}):''):'');}
function closeDialog(){if($('action-form'))saveDraft();$('editor').close();formContext=null;sync?.drain();}
async function cancelEvent(key){if(!confirm('선택한 한 번의 일정을 취소할까요? 원본 고객과 다른 일정은 유지됩니다.'))return;try{data=D.applyAction(data,{type:'schedule.cancel',payload:{eventKey:key}});$('editor').close();formContext=null;const ok=await sync.save();render();notify(ok?'일정 취소를 저장했습니다.':'취소 변경을 보관했습니다. 전송 상태를 확인하세요.');}catch(e){notify(e.message);}}
function paintInstall(){const installed=installedThisSession||matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;$('install-button').hidden=installed;$('install-button').textContent=window.hlbInstallEvent?'앱 설치':'앱 설치 안내';}
async function install(){if(installedThisSession||matchMedia('(display-mode: standalone)').matches||navigator.standalone){notify('설치된 앱으로 실행 중입니다.');return;}const event=window.hlbInstallEvent;window.hlbInstallEvent=null;paintInstall();if(event){try{await event.prompt();await event.userChoice;}catch{notify('브라우저 설치 메뉴를 확인해 주세요.');}return;}view='settings';render();notify('Chrome 메뉴의 앱 설치 / 홈 화면에 추가를 확인하세요. 설치 가능 상태가 아니면 안내만 표시됩니다.');}
function exportBackup(){if(!sync)return;const blob=new Blob([JSON.stringify(sync.exportData(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='HLB-기기보관본-'+D.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
async function actionClick(event){const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const action=el.dataset.action;let p={};try{p=JSON.parse(el.dataset.payload||'{}');}catch{return;}
 if(titles[action]){if($('editor').open&&!$('action-form'))$('editor').close();return openForm(action,p);}
 if(action==='navigate'){view=el.dataset.view;return render();}if(action==='navigate-inquiries'){view='inquiries';return render();}
 if(action==='settings'){view='settings';return render();}if(action==='close')return closeDialog();if(action==='install')return install();
 if(action==='refresh'){await sync?.retry();render();return;}if(action==='export')return exportBackup();if(action==='event')return showEvent(p.key);if(action==='cancel')return cancelEvent(p.key);
 if(action==='week-prev'||action==='week-next'){selectedDate=D.addDays(selectedDate,action==='week-prev'?-7:7);return render();}if(action==='today'){selectedDate=D.today();return render();}if(action==='day'){selectedDate=el.dataset.date;return render();}
 if(action==='inquiry'){const q=data.inquiries.find(x=>x.id===p.id);if(q)showDetail(q.name||q.phone,[['연락처',q.phone],['문의 메모',q.memo],['방문 예약',[q.visitDate,q.visitTime].filter(Boolean).join(' ')]],button('문의 수정','inquiry.save',{id:q.id})+(!q.consultId?button('상담 예약','inquiry.book',{id:q.id},'primary')+button('신청서 작성','application.save',{inquiryId:q.id}):''));}
 if(action==='student'){const s=data.students.find(x=>x.id===p.id);if(s)showDetail(s.name,[['연락처',s.ph||s.phone],['상태',s.status],['수강 시작',s.st],['등록 유형',s.schedType==='flex'?'변동':'고정'],['메모',s.memo||s.note]],button('변동 일정','schedule.once',{studentId:s.id},'primary')+button('고정 일정','schedule.fixed',{studentId:s.id}));}
 if(action==='application'){const c=data.consults.find(x=>x.id===p.id);if(c)showDetail(c.name+' · 신청서',[['연락처',c.phone],['희망 수업',c.cls],['상담 목표',c.goal],['수업 경험',c.experience],['상담 메모',c.memo],['확인',c.confirmed?'담당자 확인 완료':'기존 기록']],button('고객 등록','student.create',{name:c.name,phone:c.phone,course:c.cls},'primary'));}
 if(action==='recover'&&confirm('현재 기기의 변경을 보관본으로 남기고 서버 자료를 사용할까요?')){sync?.useServer();render();}
 if(action==='logout'){if(sync?.pending()&&!confirm('미전송 변경이 있습니다. 보관본을 내보낸 뒤 로그아웃을 권장합니다. 계속할까요?'))return;sync?.disconnect();session=null;hydrated=false;data={};$('main').textContent='로그아웃 중';location.assign('/cdn-cgi/access/logout');}
}
document.addEventListener('click',e=>actionClick(e).catch(err=>notify('작업을 완료하지 못했습니다. '+err.message)));
$('editor').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});$('editor').addEventListener('close',()=>{if(!submitting)sync?.drain();});
$('global-search').addEventListener('input',e=>{search=e.target.value;if(!['customers','inquiries','applications'].includes(view))view='customers';render();});$('search-icon').innerHTML=icon('search');
window.addEventListener('hlb-install-ready',paintInstall);window.addEventListener('appinstalled',()=>{installedThisSession=true;window.hlbInstallEvent=null;paintInstall();});
let resumed=0;function resume(){if(document.visibilityState==='hidden'||Date.now()-resumed<2000)return;resumed=Date.now();sync?.retry();}window.addEventListener('online',resume);window.addEventListener('focus',resume);document.addEventListener('visibilitychange',resume);window.addEventListener('offline',()=>paintStatus('offline'));
async function start(){nav();paintInstall();try{
 session=await VCFTransport.session();if(session.protocol!=='vs-cf-1'||!session.principal)throw Error('관리자 계정을 확인할 수 없습니다.');
 sync=VSSync.create({namespace:'vocal-studio-v2',store:sessionStorage,backupStore:localStorage,forkInstance:true,owner:()=>session?.principal||null,database:()=>VCFTransport.database(),timestamp:()=>Date.now(),frozen:()=>false,later:queueMicrotask,hydrated:()=>hydrated,
  resumeData:owner=>{try{const c=JSON.parse(localStorage.getItem('hlb-v2-cache:'+owner)||'null');return c?.owner===owner?c.data:null;}catch{return null;}},getData:()=>data,
  setData:value=>{data=value;hydrated=true;localStorage.setItem(cachedKey(),JSON.stringify({owner:session.principal,data:value}));},ready:()=>{},status:paintStatus,render,editing:()=>$('editor').open&&!submitting,validateCommit:D.assertNoNewConflicts});
 window.hlbV2={get state(){return data;},get controller(){return sync;},get view(){return view;}};sync.connect();
 if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>notify('앱 설치 준비를 확인하지 못했습니다. 브라우저에서 계속 사용할 수 있습니다.'));
 }catch(error){session=null;paintStatus('auth-required');render();}}
start();
