package com.tllhouse.hlbreplay;

import android.Manifest;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.lang.reflect.Field;
import java.util.*;

/** Executes the production Activity and config against synthetic platform boundaries. */
public final class ConnectionActivityTest {
    static int passed,failed;
    static final String KEY="vssms_"+String.join("",Collections.nCopies(41,"a"))+"_-";
    interface Check { void run() throws Exception; }
    static void test(String name,Check c) { try { c.run(); passed++; System.out.println("PASS "+name); } catch(Throwable e) { failed++; System.out.println("FAIL "+name+": "+e.getClass().getSimpleName()+" "+e.getMessage()); } }
    static void ok(boolean b,String msg) {if(!b)throw new AssertionError(msg);}
    static Object field(MainActivity a,String name)throws Exception {Field f=MainActivity.class.getDeclaredField(name);f.setAccessible(true);return f.get(a);}
    static EditText input(MainActivity a,String name)throws Exception{return (EditText)field(a,name);}
    static String status(MainActivity a)throws Exception{return ((TextView)field(a,"status")).getText().toString();}
    static List<View> views(MainActivity a){return ((LinearLayout)((ScrollView)a.root).child).children;}
    static Button button(MainActivity a,String label){for(View v:views(a))if(v instanceof Button && ((Button)v).getText().toString().equals(label))return (Button)v;throw new AssertionError("button missing: "+label);}
    static void tap(MainActivity a,String label){ok(button(a,label).performClick(),"button not enabled: "+label);}
    static void poll(MainActivity a)throws Exception{Handler h=(Handler)field(a,"handler");for(int i=0;i<4;i++)h.tick();}
    static MainActivity app(){RelayScheduler.fail=false;MainActivity a=new MainActivity();a.onCreate(new Bundle());a.onResume();return a;}
    static void valid(MainActivity a)throws Exception{input(a,"url").setText("https://relay.example");input(a,"token").setText(KEY);}
    static void clipboard(MainActivity a,String text){a.clipboard.clip=ClipData.newPlainText("key",text);}
    static void paste(MainActivity a){tap(a,"연결키 붙여넣기");}
    static void persistent(MainActivity a,String diagnostic)throws Exception{ok(status(a).contains(diagnostic),"specific diagnostic missing");String s=status(a);poll(a);ok(status(a).equals(s),"poll overwrote local diagnostic");ok(!s.contains(KEY),"key disclosed");}
    static void noStart(MainActivity a){ok(!new RelayConfig(a).enabled,"paste must not start");ok(!a.preferences.values.containsKey("token"),"draft persisted");}
    public static void main(String[] args) throws Exception {
        test("URL diagnostic survives polling",()->{MainActivity a=app();valid(a);input(a,"url").setText("http://unsafe.example/path?private=synthetic");tap(a,"연결 시작");persistent(a,"HTTPS");ok(!status(a).contains("unsafe.example"),"URL disclosed");ok(input(a,"token").getText().length()==0,"start must wipe draft");});
        for(String raw:new String[]{"","https://relay.example/path","https://relay.example/?key=synthetic","https://relay.example/#synthetic","https://user:synthetic@relay.example","https://relay.example:444","hlb://relay.example"})test("unsafe URL rejected #"+Arrays.asList("","https://relay.example/path","https://relay.example/?key=synthetic","https://relay.example/#synthetic","https://user:synthetic@relay.example","https://relay.example:444","hlb://relay.example").indexOf(raw),()->{MainActivity a=app();valid(a);input(a,"url").setText(raw);tap(a,"연결 시작");persistent(a,"HTTPS");ok(!status(a).contains("synthetic"),"unsafe URL input disclosed");noStart(a);});
        test("empty key has distinct persistent diagnostic",()->{MainActivity a=app();tap(a,"연결 시작");persistent(a,"연결키를 입력");noStart(a);});
        test("malformed key has distinct persistent diagnostic",()->{MainActivity a=app();input(a,"token").setText("broken!synthetic-key");tap(a,"연결 시작");persistent(a,"연결키 형식");ok(!status(a).contains("broken"),"bad draft disclosed");});
        test("URL errors clear only on valid URL action",()->{MainActivity a=app();valid(a);input(a,"url").setText("http://bad.example");tap(a,"연결 시작");input(a,"url").setText("bad");persistent(a,"HTTPS");input(a,"token").setText(KEY);persistent(a,"HTTPS");input(a,"url").setText("https://relay.example");poll(a);ok(!status(a).contains("HTTPS"),"correct URL did not clear");});
        test("key errors clear only on valid key action",()->{MainActivity a=app();tap(a,"연결 시작");input(a,"token").setText("bad");persistent(a,"연결키를 입력");clipboard(a,KEY);paste(a);poll(a);ok(!status(a).contains("연결키를 입력"),"paste did not clear error");ok(input(a,"token").getText().toString().equals(KEY),"paste bytes changed");noStart(a);});
        test("foreground owner paste exact server key without auto-start",()->{MainActivity a=app();clipboard(a,KEY);paste(a);ok(input(a,"token").getText().toString().equals(KEY),"paste mismatch");ok(a.clipboard.reads==1 && a.clipboardServices==1,"one explicit read required");ok(a.clipboard.writes==0,"clipboard export");noStart(a);});
        test("no automatic clipboard reads on create resume poll pause",()->{MainActivity a=app();clipboard(a,KEY);poll(a);a.onPause();a.onResume();poll(a);a.onDestroy();ok(a.clipboard.reads==0 && a.clipboardServices==0,"automatic clipboard access");});
        test("no paste while paused or before resume",()->{MainActivity a=new MainActivity();a.onCreate(new Bundle());clipboard(a,KEY);paste(a);ok(a.clipboard.reads==0,"pre-resume read");a.onResume();a.onPause();paste(a);ok(a.clipboard.reads==0,"paused read");});
        String[] malformed={" "+KEY,KEY+" ",KEY+"\n",KEY+"\r\n",KEY+"\t",KEY+"\u200b",KEY+"!","short","",String.join("",Collections.nCopies(1025,"a")),"https://relay.example/?token="+KEY,"hlb://pair/"+KEY,"ordinary16chars1","123456",KEY.substring(0,20)+" "+KEY.substring(21),KEY.substring(0,KEY.length()-1),KEY+"a","VSSMS_"+KEY.substring(6),String.join("",Collections.nCopies(64,"a"))};
        for(int i=0;i<malformed.length;i++){final String raw=malformed[i];test("invalid raw paste rejected #"+i,()->{MainActivity a=app();input(a,"token").setText(KEY);clipboard(a,raw);paste(a);ok(input(a,"token").getText().length()==0,"invalid paste left acceptable draft");persistent(a,"연결키");noStart(a);});}
        test("manual whitespace key also rejected",()->{MainActivity a=app();input(a,"token").setText(KEY+"\n");tap(a,"연결 시작");persistent(a,"연결키 형식");noStart(a);});
        test("owner paste does not clear unresolved URL error",()->{MainActivity a=app();valid(a);input(a,"url").setText("http://bad.example");tap(a,"연결 시작");clipboard(a,KEY);paste(a);persistent(a,"HTTPS");});
        test("same-generation successful sync clears local resume error",()->{MainActivity a=app();valid(a);tap(a,"연결 시작");a.onPause();RelayScheduler.fail=true;a.onResume();persistent(a,"백그라운드");a.preferences.edit().putString("status","연결 확인 완료").putLong("lastSync",1234).commit();poll(a);ok(status(a).contains("연결 확인 완료"),"same-generation success hidden");RelayScheduler.fail=false;});
        test("plain text URI payload never coerced",()->{MainActivity a=app();ClipData.Item item=new ClipData.Item(KEY);item.uri=android.net.Uri.parse("content://external/private");a.clipboard.clip=new ClipData("text/plain",item);paste(a);ok(item.coerces==0,"URI coerced");ok(input(a,"token").getText().length()==0,"URI imported");persistent(a,"텍스트");});
        test("plain text Intent payload rejected",()->{MainActivity a=app();ClipData.Item item=new ClipData.Item(KEY);item.intent=new Intent("external");a.clipboard.clip=new ClipData("text/plain",item);paste(a);ok(item.coerces==0 && input(a,"token").getText().length()==0,"Intent imported");});
        test("HTML-only clipboard rejected",()->{MainActivity a=app();a.clipboard.clip=new ClipData("text/html",new ClipData.Item(KEY));paste(a);persistent(a,"텍스트");noStart(a);});
        test("multiple clipboard items rejected",()->{MainActivity a=app();a.clipboard.clip=new ClipData("text/plain",new ClipData.Item(KEY),new ClipData.Item(KEY));paste(a);persistent(a,"텍스트");noStart(a);});
        test("missing clipboard and missing text handled",()->{MainActivity a=app();paste(a);persistent(a,"복사");a.clipboard.clip=new ClipData("text/plain",new ClipData.Item(null));paste(a);persistent(a,"텍스트");});
        test("clipboard denial is persistent and retry recovers",()->{MainActivity a=app();a.clipboard.fail=true;paste(a);persistent(a,"클립보드");a.clipboard.fail=false;clipboard(a,KEY);paste(a);ok(input(a,"token").getText().toString().equals(KEY),"retry failed");poll(a);ok(!status(a).contains("클립보드"),"stale clipboard error");});
        test("successful start shows current status and enabled controls",()->{MainActivity a=app();tap(a,"연결 시작");clipboard(a,KEY);paste(a);tap(a,"연결 시작");ok(new RelayConfig(a).enabled,"not enabled");poll(a);ok(status(a).contains("연결 확인 중"),"success hidden");ok(!button(a,"연결 시작").isEnabled() && button(a,"연결 중지").isEnabled(),"start/stop controls");ok(!input(a,"url").isEnabled() && !input(a,"token").isEnabled() && !button(a,"연결키 붙여넣기").isEnabled(),"draft controls enabled");ok(button(a,"수신 전화 연결에 동의하기").isEnabled(),"call control disabled");ok(input(a,"token").getText().length()==0,"successful start draft retained");a.clipboard.reads=0;button(a,"연결키 붙여넣기").performClick();ok(a.clipboard.reads==0,"paste enabled while connected");});
        test("new generation clears stale local error",()->{MainActivity a=app();tap(a,"연결 시작");RelayConfig.start(a,"https://new.example",KEY);a.preferences.edit().putString("status","현재 연결 확인 완료").putLong("lastSync",1000).commit();poll(a);ok(status(a).contains("현재 연결 확인 완료") && status(a).contains("최근 확인"),"new generation hidden");});
        test("changed config origin clears local error",()->{MainActivity a=app();tap(a,"연결 시작");a.preferences.edit().putString("origin","https://new.example").commit();poll(a);ok(!status(a).contains("연결키를 입력"),"different origin hidden");});
        test("pause wipes token and removes refresh callbacks",()->{MainActivity a=app();valid(a);a.onPause();ok(input(a,"token").getText().length()==0,"pause did not wipe");ok(((Handler)field(a,"handler")).queue.isEmpty(),"refresh survived pause");a.onResume();ok(input(a,"token").getText().length()==0,"resume restored draft");});
        test("stop wipes draft even if saving stop fails",()->{MainActivity a=app();valid(a);tap(a,"연결 시작");input(a,"token").setText(KEY);a.preferences.failCommit=true;tap(a,"연결 중지");ok(input(a,"token").getText().length()==0,"failed stop retained draft");persistent(a,"중지 상태");});
        test("successful stop resets controls and clears persisted key",()->{MainActivity a=app();valid(a);tap(a,"연결 시작");tap(a,"연결 중지");poll(a);ok(!new RelayConfig(a).enabled && !a.preferences.values.containsKey("token"),"stop retained active config");ok(button(a,"연결 시작").isEnabled() && button(a,"연결키 붙여넣기").isEnabled() && !button(a,"연결 중지").isEnabled(),"stop controls");});
        for(String permission:new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS,Manifest.permission.SEND_SMS})test("each SMS permission is required: "+permission,()->{MainActivity a=app();a.denied.add(permission);valid(a);tap(a,"연결 시작");ok(a.permissionRequests==1 && a.requested.length==3,"permissions not requested");noStart(a);ok(input(a,"token").getText().length()==0,"permission start retained draft");a.onRequestPermissionsResult(42,a.requested,new int[]{0,0,0});persistent(a,"문자 읽기·수신·발송");noStart(a);});
        test("owner-authorized permission continuation consumes key once with pause field wipe",()->{MainActivity a=app();a.denied.add(Manifest.permission.SEND_SMS);valid(a);tap(a,"연결 시작");noStart(a);a.onPause();ok(input(a,"token").getText().length()==0,"pause field not wiped");a.denied.clear();a.onRequestPermissionsResult(42,a.requested,new int[]{0,0,0});ok(new RelayConfig(a).enabled,"authorized grant did not connect");ok(field(a,"permissionToken")==null && field(a,"permissionOrigin")==null,"completed request retained");String generation=new RelayConfig(a).generation;a.onResume();a.onRequestPermissionsResult(42,a.requested,new int[]{0,0,0});ok(new RelayConfig(a).generation.equals(generation),"callback replayed start");poll(a);ok(status(a).contains("연결 확인 중"),"grant success hidden");});
        test("permission denial discards pending key",()->{MainActivity a=app();a.denied.add(Manifest.permission.SEND_SMS);valid(a);tap(a,"연결 시작");a.onRequestPermissionsResult(42,a.requested,new int[]{0,0,-1});ok(field(a,"permissionToken")==null,"denial retained key");a.denied.clear();a.onRequestPermissionsResult(42,a.requested,new int[]{0,0,0});noStart(a);});
        test("new generation invalidates pending permission continuation",()->{MainActivity a=app();a.denied.add(Manifest.permission.SEND_SMS);valid(a);tap(a,"연결 시작");a.denied.clear();RelayConfig.start(a,"https://new.example",KEY);RelayConfig.stop(a,"새 연결 중지");String generation=new RelayConfig(a).generation;a.onRequestPermissionsResult(42,a.requested,new int[]{0,0,0});ok(!new RelayConfig(a).enabled && new RelayConfig(a).generation.equals(generation),"stale grant restarted");ok(field(a,"permissionToken")==null,"stale request retained key");});
        test("changed origin invalidates pending permission continuation",()->{MainActivity a=app();a.denied.add(Manifest.permission.SEND_SMS);valid(a);tap(a,"연결 시작");a.denied.clear();a.preferences.edit().putString("origin","https://new.example").commit();a.onRequestPermissionsResult(42,a.requested,new int[]{0,0,0});noStart(a);ok(field(a,"permissionToken")==null,"changed config retained request");});
        test("destroy discards pending permission key",()->{MainActivity a=app();a.denied.add(Manifest.permission.SEND_SMS);valid(a);tap(a,"연결 시작");a.onPause();a.onDestroy();ok(field(a,"permissionToken")==null && field(a,"permissionOrigin")==null,"destroy retained key");});
        test("old permission result cannot cover new success",()->{MainActivity a=app();valid(a);tap(a,"연결 시작");a.onRequestPermissionsResult(42,new String[0],new int[0]);poll(a);ok(status(a).contains("연결 확인 중"),"stale permission result covered success");});
        test("config save failure accurately diagnosed, draft wiped",()->{MainActivity a=app();a.preferences.failCommit=true;valid(a);tap(a,"연결 시작");persistent(a,"저장");ok(input(a,"token").getText().length()==0,"failure retained draft");noStart(a);});
        test("scheduler failure accurately diagnosed and retry clears",()->{MainActivity a=app();RelayScheduler.fail=true;valid(a);tap(a,"연결 시작");persistent(a,"백그라운드");ok(!new RelayConfig(a).enabled,"failed setup remained active");RelayScheduler.fail=false;valid(a);tap(a,"연결 시작");poll(a);ok(status(a).contains("연결 확인 중"),"retry hidden");});
        test("observer failure accurately diagnosed",()->{MainActivity a=app();a.resolver.fail=true;valid(a);tap(a,"연결 시작");persistent(a,"문자 수신 상태");ok(!new RelayConfig(a).enabled,"observer failure active");});
        test("resume scheduling error survives refresh",()->{MainActivity a=app();a.onPause();RelayScheduler.fail=true;a.onResume();persistent(a,"백그라운드");RelayScheduler.fail=false;});
        test("secure password/no-save/no-autofill/no-export preserved",()->{MainActivity a=app();EditText key=input(a,"token");ok((a.window.flags & WindowManager.LayoutParams.FLAG_SECURE)!=0,"secure flag missing");ok(!key.save && !input(a,"url").save,"draft saved");ok(key.autofill==View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS && input(a,"url").autofill==key.autofill,"autofill allowed");ok(!key.longClickable && !key.selectable,"key copy allowed");ok((key.inputType & android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD)!=0,"key not masked");ok(a.clipboard.writes==0,"exported clipboard");});
        System.out.println("RESULT "+passed+" passed, "+failed+" failed");if(failed>0)System.exit(1);
    }
}
