// Host-only Android UI/clipboard/Handler surfaces; never part of an APK.
export const stubs = {
'android/Manifest.java': `package android; public class Manifest { public static class permission { public static final String READ_SMS="read",RECEIVE_SMS="receive",SEND_SMS="send",READ_CONTACTS="contacts"; } }`,
'android/content/Context.java': `package android.content;
import java.util.*; import android.content.pm.PackageManager;
public class Context {
 public static final int MODE_PRIVATE=0; public static final String CLIPBOARD_SERVICE="clipboard";
 public Memory preferences=new Memory(); public Set<String> denied=new HashSet<>(); public ClipboardManager clipboard=new ClipboardManager(); public ContentResolver resolver=new ContentResolver();
 public android.app.role.RoleManager role=new android.app.role.RoleManager(); public int clipboardServices;
 public SharedPreferences getSharedPreferences(String n,int mode){return preferences;}
 public int checkSelfPermission(String p){return denied.contains(p)?-1:0;}
 public Object getSystemService(String n){clipboardServices++;return clipboard;}
 @SuppressWarnings("unchecked") public <T> T getSystemService(Class<T> c){return c==android.app.role.RoleManager.class?(T)role:null;}
 public ContentResolver getContentResolver(){return resolver;} public String getPackageName(){return "com.tllhouse.hlbreplay";}
 public android.content.res.Resources getResources(){return new android.content.res.Resources();}
 public static class Memory implements SharedPreferences {
  public final Map<String,Object> values=new HashMap<>(); public boolean failCommit;
  public String getString(String k,String d){return (String)values.getOrDefault(k,d);} public long getLong(String k,long d){return (Long)values.getOrDefault(k,d);} public boolean getBoolean(String k,boolean d){return (Boolean)values.getOrDefault(k,d);}
  @SuppressWarnings("unchecked") public Set<String> getStringSet(String k,Set<String> d){return new HashSet<>((Set<String>)values.getOrDefault(k,d));}
  public Editor edit(){return new Editor(){ Map<String,Object> next=new HashMap<>(values); public Editor putString(String k,String v){next.put(k,v);return this;} public Editor putLong(String k,long v){next.put(k,v);return this;} public Editor putBoolean(String k,boolean v){next.put(k,v);return this;} public Editor putStringSet(String k,Set<String> v){next.put(k,new HashSet<>(v));return this;} public Editor remove(String k){next.remove(k);return this;} public boolean commit(){if(failCommit)return false;values.clear();values.putAll(next);return true;} };}
 }
}`,
'android/content/ContentResolver.java': `package android.content; import android.database.ContentObserver; import android.net.Uri; public class ContentResolver { public boolean fail; public void unregisterContentObserver(ContentObserver o){} public void registerContentObserver(Uri u,boolean b,ContentObserver o){if(fail)throw new SecurityException();} }`,
'android/content/res/Resources.java': `package android.content.res; public class Resources { public android.util.DisplayMetrics getDisplayMetrics(){return new android.util.DisplayMetrics();} }`,
'android/util/DisplayMetrics.java': `package android.util; public class DisplayMetrics { public float density=1; }`,
'android/content/ClipboardManager.java': `package android.content; public class ClipboardManager { public ClipData clip; public int reads,writes; public boolean fail; public ClipData getPrimaryClip(){reads++;if(fail)throw new SecurityException();return clip;} public void setPrimaryClip(ClipData c){writes++;clip=c;} }`,
'android/content/ClipDescription.java': `package android.content; public class ClipDescription { public static final String MIMETYPE_TEXT_PLAIN="text/plain"; public String mime; public ClipDescription(String m){mime=m;} public boolean hasMimeType(String m){return mime.equals(m);} }`,
'android/content/ClipData.java': `package android.content; import android.net.Uri; public class ClipData { public ClipDescription description; public Item[] items; public ClipData(String mime,Item... i){description=new ClipDescription(mime);items=i;} public static ClipData newPlainText(CharSequence label,CharSequence text){return new ClipData("text/plain",new Item(text));} public int getItemCount(){return items.length;} public Item getItemAt(int i){return items[i];} public ClipDescription getDescription(){return description;} public static class Item { public CharSequence text; public Uri uri; public Intent intent; public int coerces; public Item(CharSequence t){text=t;} public CharSequence getText(){return text;} public Uri getUri(){return uri;} public Intent getIntent(){return intent;} public CharSequence coerceToText(Context c){coerces++;throw new AssertionError("external coercion");} } }`,
'android/app/Activity.java': `package android.app; import android.content.*; import android.os.Bundle; import android.view.*; public class Activity extends Context { public static final int RESULT_OK=-1; public View root; public Window window=new Window(); public int permissionRequests; public String[] requested; public void onCreate(Bundle b){} public void onResume(){} public void onPause(){} public void onDestroy(){} protected void onActivityResult(int r,int s,Intent i){} public void onRequestPermissionsResult(int r,String[] p,int[] s){} public void requestPermissions(String[] p,int r){permissionRequests++;requested=p;} public void setContentView(View v){root=v;} public Window getWindow(){return window;} public void startActivity(Intent i){} public void startActivityForResult(Intent i,int r){} }`,
'android/app/AlertDialog.java': `package android.app; import android.content.Context; public class AlertDialog { public static class Builder { public interface Listener {void onClick(Object d,int w);} public Builder(Context c){} public Builder setTitle(String s){return this;} public Builder setMessage(String s){return this;} public Builder setNegativeButton(String s,Listener l){return this;} public Builder setPositiveButton(String s,Listener l){return this;} public void show(){} } }`,
'android/app/role/RoleManager.java': `package android.app.role; import android.content.Intent; public class RoleManager { public static final String ROLE_CALL_SCREENING="screen"; public boolean isRoleAvailable(String s){return true;} public boolean isRoleHeld(String s){return true;} public Intent createRequestRoleIntent(String s){return new Intent(s);} }`,
'android/os/Handler.java': `package android.os; import java.util.*; public class Handler { public List<Runnable> queue=new ArrayList<>(); public Handler(Looper l){} public boolean post(Runnable r){queue.add(r);return true;} public boolean postDelayed(Runnable r,long t){queue.add(r);return true;} public void removeCallbacks(Runnable r){queue.removeIf(x->x==r);} public void tick(){if(!queue.isEmpty())queue.remove(0).run();} }`,
'android/os/Looper.java': `package android.os; public class Looper { public static Looper getMainLooper(){return new Looper();} }`,
'android/database/ContentObserver.java': `package android.database; import android.os.Handler; public class ContentObserver {public ContentObserver(Handler h){} public void onChange(boolean b){} }`,
'android/provider/Settings.java': `package android.provider; public class Settings { public static final String ACTION_MANAGE_DEFAULT_APPS_SETTINGS="defaults",ACTION_APPLICATION_DETAILS_SETTINGS="details"; }`,
'android/provider/Telephony.java': `package android.provider; public class Telephony { public static class Sms { public static final android.net.Uri CONTENT_URI=android.net.Uri.parse("content://sms"); } }`,
'android/text/InputType.java': `package android.text; public class InputType { public static final int TYPE_CLASS_TEXT=1,TYPE_TEXT_VARIATION_URI=16,TYPE_TEXT_VARIATION_PASSWORD=128,TYPE_TEXT_FLAG_NO_SUGGESTIONS=524288; }`,
'android/text/Editable.java': `package android.text; public interface Editable extends CharSequence {}`,
'android/text/TextWatcher.java': `package android.text; public interface TextWatcher {void beforeTextChanged(CharSequence s,int a,int c,int f);void onTextChanged(CharSequence s,int a,int b,int c);void afterTextChanged(Editable e);}`,
'android/view/View.java': `package android.view; import android.content.Context; public class View { public static final int IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS=8; public boolean enabled=true,save=true,longClickable=true,selectable; public int autofill; public interface OnClickListener{void onClick(View v);} public interface OnApplyWindowInsetsListener{WindowInsets onApplyWindowInsets(View v,WindowInsets i);} public OnClickListener click; public View(Context c){} public void setPadding(int a,int b,int c,int d){} public void setOnApplyWindowInsetsListener(OnApplyWindowInsetsListener l){} public void setOnClickListener(OnClickListener l){click=l;} public boolean performClick(){if(!enabled||click==null)return false;click.onClick(this);return true;} public void setEnabled(boolean b){enabled=b;} public boolean isEnabled(){return enabled;} public void setSaveEnabled(boolean b){save=b;} public void setImportantForAutofill(int a){autofill=a;} public void setLongClickable(boolean b){longClickable=b;} }`,
'android/view/Window.java': `package android.view; public class Window {public int flags;public void addFlags(int f){flags|=f;} }`,
'android/view/WindowManager.java': `package android.view; public class WindowManager { public static class LayoutParams { public static final int FLAG_SECURE=8192; } }`,
'android/view/WindowInsets.java': `package android.view; public class WindowInsets { public android.graphics.Insets getInsets(int t){return new android.graphics.Insets();} public int getSystemWindowInsetLeft(){return 0;} public int getSystemWindowInsetTop(){return 0;} public int getSystemWindowInsetRight(){return 0;} public int getSystemWindowInsetBottom(){return 0;} public static class Type { public static int systemBars(){return 1;}public static int ime(){return 2;} } }`,
'android/graphics/Insets.java': `package android.graphics; public class Insets {public int left,top,right,bottom;}`,
'android/widget/TextView.java': `package android.widget; import android.content.Context; import android.view.View; public class TextView extends View {protected CharSequence text="";public TextView(Context c){super(c);} public void setText(CharSequence s){text=s;}public CharSequence getText(){return text;}public void setTextSize(int s){} }`,
'android/widget/EditText.java': `package android.widget; import android.content.Context; import android.text.*; import java.util.*; public class EditText extends TextView { public int inputType;public List<TextWatcher> watchers=new ArrayList<>();public EditText(Context c){super(c);} public void setSingleLine(boolean b){}public void setHint(String s){}public void setInputType(int t){inputType=t;}public void setTextIsSelectable(boolean b){selectable=b;}public void addTextChangedListener(TextWatcher w){watchers.add(w);}public void setText(CharSequence s){super.setText(s);for(TextWatcher w:watchers)w.afterTextChanged(new E(s.toString()));}static class E implements Editable {String s;E(String t){s=t;}public int length(){return s.length();}public char charAt(int i){return s.charAt(i);}public CharSequence subSequence(int a,int b){return s.substring(a,b);}public String toString(){return s;} } }`,
'android/widget/Button.java': `package android.widget; import android.content.Context; public class Button extends TextView {public Button(Context c){super(c);} }`,
'android/widget/LinearLayout.java': `package android.widget; import android.content.Context; import android.view.View; import java.util.*; public class LinearLayout extends View {public static final int VERTICAL=1;public List<View> children=new ArrayList<>();public LinearLayout(Context c){super(c);}public void setOrientation(int o){}public void addView(View v){children.add(v);} }`,
'android/widget/ScrollView.java': `package android.widget; import android.content.Context; import android.view.View; public class ScrollView extends View {public View child;public ScrollView(Context c){super(c);}public void addView(View v){child=v;} }`,
'com/tllhouse/hlbreplay/RelayScheduler.java': `package com.tllhouse.hlbreplay; import android.content.Context; final class RelayScheduler {static boolean fail;static int scheduled,cancellations;static void ensure(Context c){if(fail)throw new IllegalStateException();scheduled++;}static void soon(Context c){if(fail)throw new IllegalStateException();scheduled++;}static void cancel(Context c){cancellations++;}}`,
'com/tllhouse/hlbreplay/ManagementLauncher.java': `package com.tllhouse.hlbreplay; import android.content.Context; final class ManagementLauncher {static boolean open(Context c){return true;}static boolean openPrivacy(Context c){return true;}}`
};
